# Generated by Django 5.2.1 on 2026-04-25 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_project_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                related_name="projects",
                through="main.ProjectMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
